### ISSUE TITLE
esbuild not found

### ISSUE THREAD

**Issue by taygetea** [mnaoumov/obsidian-fix-require-modules#3]
windows, on both my main vault with lots of plugins and a fresh one with just BRAT. 
![image](https://github.com/user-attachments/assets/bf2984d9-cf78-4d04-a5f4-9a7910c5cf18)
looks like you were working on this recently? seems like your fix didnt take. obsidian-dev-utils loads fine if i do that manually.

**Comment by taygetea** [comment]
there are two repos named "obsidian-dev-utils" and i seem to have tried the wrong one (https://github.com/RyotaUshio/obsidian-dev-utils/), ill try yours now.

**Comment by taygetea** [comment]
ah, confusingly that one *is* a valid plugin and yours isnt.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/mnaoumov/obsidian-fix-require-modules/releases/tag/5.0.3

**Comment by mnaoumov** [comment]
@taygetea you mentioned you tried to do something with `obsidian-dev-utils`. Why? What made you think it's the problem?

**Comment by taygetea** [comment]
on a brief skim of [this](https://github.com/mnaoumov/obsidian-fix-require-modules/blob/81cad7b912d5cf6a7cc4cb0fa3bb3bd9159536d1/scripts/fixRequireEsbuildPlugin.ts#L12) code i guessed it might also break if esbuild was having some systemwide issue. i dont have much experience with the js ecosystem but did some messy exploratory stuff with a big project a few days ago and was a little worried i had broken something on my system.
